# Dependencies
markdown:         kramdown
highlighter:      pygments

plugins: [jekyll-paginate]  
# Permalinks
permalink:        pretty

# Setup
title:            Pairs of pants
tagline:           
description:      'musings on pairs of pants'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Tudor Caba'
  url:            

paginate:         5

# Custom vars
version:          

github:
  repo:           
